import { palette } from '../../core/design/tokens';
import type { GameModeMeta } from '../../domain';

/**
 * The master catalogue of every game mode's metadata — the single source the
 * home grid, lobby and game host read from. Playable modes attach their
 * gameplay component in `registry.ts`; `status: 'soon'` modes are announced
 * here and render a polished "coming soon" screen.
 */

export const MODE_IDS = {
  stadtLandFluss: 'stadt_land_fluss',
  millionaire: 'millionaire',
  higherLower: 'higher_lower',
  reaction: 'reaction',
  guessPrice: 'guess_price',
  logoQuiz: 'logo_quiz',
  pictureQuiz: 'picture_quiz',
  musicQuiz: 'music_quiz',
} as const;

export const MODE_META: Record<string, GameModeMeta> = {
  [MODE_IDS.stadtLandFluss]: {
    id: MODE_IDS.stadtLandFluss,
    title: 'Stadt Land Fluss',
    tagline: 'Über 300 Kategorien',
    description:
      'Der Klassiker, neu gedacht. Finde zu jedem Buchstaben passende Begriffe in hunderten Kategorien – von Anime bis Pokémon.',
    emoji: '✏️',
    icon: 'create',
    category: 'word',
    status: 'ready',
    color: palette.green,
    gradient: [palette.green, palette.cyanDeep],
    accent: {
      primary: palette.green,
      primaryBright: '#5BE89A',
      primaryDeep: palette.greenDeep,
      primaryGradient: [palette.green, palette.cyanDeep],
    },
    supports: { solo: true, local: true, online: false, bots: true },
    minPlayers: 1,
    maxPlayers: 8,
    estimatedMinutes: 5,
    difficulties: ['easy', 'medium', 'hard', 'expert'],
  },
  [MODE_IDS.millionaire]: {
    id: MODE_IDS.millionaire,
    title: 'Wer wird Millionär',
    tagline: '15 Fragen zur Million',
    description:
      'Beantworte 15 Fragen und arbeite dich zur Million. Mit echtem TV-Feeling, vier Jokern und steigender Spannung.',
    emoji: '💰',
    icon: 'cash',
    category: 'quiz',
    status: 'ready',
    color: palette.gold,
    gradient: ['#2A4BA0', '#0B1E54'],
    accent: {
      primary: palette.gold,
      primaryBright: '#FFE07A',
      primaryDeep: palette.goldDeep,
      primaryGradient: [palette.gold, palette.goldDeep],
      canvasGradient: ['#10245E', palette.night0],
    },
    supports: { solo: true, local: false, online: false, bots: false },
    minPlayers: 1,
    maxPlayers: 1,
    estimatedMinutes: 6,
    difficulties: ['easy', 'medium', 'hard'],
  },
  [MODE_IDS.higherLower]: {
    id: MODE_IDS.higherLower,
    title: 'Higher or Lower',
    tagline: 'Mehr oder weniger?',
    description:
      'Hat es mehr oder weniger? Errate, welcher Begriff den höheren Wert hat – und baue die längste Serie auf.',
    emoji: '📈',
    icon: 'swap-vertical',
    category: 'guess',
    status: 'ready',
    color: palette.magenta,
    gradient: [palette.orange, palette.magenta],
    accent: {
      primary: palette.magenta,
      primaryBright: '#FF7AAE',
      primaryDeep: palette.magentaDeep,
      primaryGradient: [palette.orange, palette.magenta],
    },
    supports: { solo: true, local: true, online: false, bots: true },
    minPlayers: 1,
    maxPlayers: 6,
    estimatedMinutes: 3,
  },
  [MODE_IDS.reaction]: {
    id: MODE_IDS.reaction,
    title: 'Schlag den Raab',
    tagline: 'Schnelle Minispiele',
    description:
      'Eine Serie blitzschneller Minispiele: Reaktion, Merken, Kopfrechnen, Schätzen und mehr. Wer hat die besten Nerven?',
    emoji: '⚡',
    icon: 'flash',
    category: 'reaction',
    status: 'ready',
    color: palette.orange,
    gradient: [palette.red, palette.orange],
    accent: {
      primary: palette.orange,
      primaryBright: '#FFB070',
      primaryDeep: '#C85A14',
      primaryGradient: [palette.red, palette.orange],
    },
    supports: { solo: true, local: true, online: false, bots: true },
    minPlayers: 1,
    maxPlayers: 8,
    estimatedMinutes: 4,
  },
  [MODE_IDS.guessPrice]: {
    id: MODE_IDS.guessPrice,
    title: 'Der Preis ist heiß',
    tagline: 'Schätze den Preis',
    description:
      'Wie viel kostet das? Schätze den Preis von Produkten so genau wie möglich – je näher dran, desto mehr Punkte.',
    emoji: '🏷️',
    icon: 'pricetag',
    category: 'guess',
    status: 'ready',
    color: palette.lime,
    gradient: [palette.lime, palette.green],
    accent: {
      primary: palette.green,
      primaryBright: '#9CF15B',
      primaryDeep: palette.greenDeep,
      primaryGradient: [palette.lime, palette.green],
    },
    supports: { solo: true, local: true, online: false, bots: true },
    minPlayers: 1,
    maxPlayers: 6,
    estimatedMinutes: 3,
  },
  [MODE_IDS.logoQuiz]: {
    id: MODE_IDS.logoQuiz,
    title: 'Logo Quiz',
    tagline: 'Tausende Logos',
    description: 'Erkenne Marken an ihren Logos – von einfach bis knifflig, über viele Kategorien.',
    emoji: '🔵',
    icon: 'apps',
    category: 'guess',
    status: 'soon',
    color: palette.violetBright,
    gradient: [palette.violetBright, palette.violetDeep],
    accent: { primary: palette.violetBright },
    supports: { solo: true, local: true, online: true, bots: true },
    minPlayers: 1,
    maxPlayers: 6,
    estimatedMinutes: 4,
  },
  [MODE_IDS.pictureQuiz]: {
    id: MODE_IDS.pictureQuiz,
    title: 'Bilder Quiz',
    tagline: 'Errate das Bild',
    description: 'Länder, Autos, Tiere, Stars und mehr – errate, was auf dem Bild zu sehen ist.',
    emoji: '🖼️',
    icon: 'image',
    category: 'guess',
    status: 'soon',
    color: palette.cyan,
    gradient: [palette.cyan, palette.blue],
    accent: { primary: palette.cyan },
    supports: { solo: true, local: true, online: true, bots: true },
    minPlayers: 1,
    maxPlayers: 6,
    estimatedMinutes: 4,
  },
  [MODE_IDS.musicQuiz]: {
    id: MODE_IDS.musicQuiz,
    title: 'Musik Quiz',
    tagline: 'Song · Interpret · Intro',
    description: 'Errate Songs, Interpreten und Intros, bevor die Zeit abläuft.',
    emoji: '🎵',
    icon: 'musical-notes',
    category: 'guess',
    status: 'soon',
    color: palette.magenta,
    gradient: [palette.magenta, palette.violet],
    accent: { primary: palette.magenta },
    supports: { solo: true, local: true, online: true, bots: true },
    minPlayers: 1,
    maxPlayers: 6,
    estimatedMinutes: 4,
  },
};

/** Stable display order for the mode grid (ready modes first). */
export const MODE_ORDER: string[] = [
  MODE_IDS.stadtLandFluss,
  MODE_IDS.millionaire,
  MODE_IDS.reaction,
  MODE_IDS.higherLower,
  MODE_IDS.guessPrice,
  MODE_IDS.logoQuiz,
  MODE_IDS.pictureQuiz,
  MODE_IDS.musicQuiz,
];

export const ALL_MODE_METAS: GameModeMeta[] = MODE_ORDER.map((id) => MODE_META[id]);
